-- MySQL Script generated by MySQL Workbench
-- ned 05 jan 2020 22:36:16 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema baza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baza` DEFAULT CHARACTER SET utf8 ;
USE `baza` ;

-- -----------------------------------------------------
-- Table `baza`.`naslov`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`naslov` ;

CREATE TABLE IF NOT EXISTS `baza`.`naslov` (
  `id_naslov` INT(11) NOT NULL AUTO_INCREMENT,
  `postna_stevilka` INT(20) NOT NULL,
  `mesto` VARCHAR(45) NOT NULL,
  `ulica` VARCHAR(45) NOT NULL,
  `hisna_stevilka` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_naslov`),
  UNIQUE INDEX `id_naslov_UNIQUE` (`id_naslov` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`uporabnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`uporabnik` ;

CREATE TABLE IF NOT EXISTS `baza`.`uporabnik` (
  `id_uporabnik` INT(11) NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `priimek` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `geslo` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL,
  `uloga` VARCHAR(45) NOT NULL,
  `fk_id_naslov` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_uporabnik`),
  UNIQUE INDEX `id_uporabnik_UNIQUE` (`id_uporabnik` ASC),
  INDEX `fk_uporabnik_naslov_idx` (`fk_id_naslov` ASC),
  CONSTRAINT `fk_id_naslov`
    FOREIGN KEY (`fk_id_naslov`)
    REFERENCES `baza`.`naslov` (`id_naslov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`kosarica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`kosarica` ;

CREATE TABLE IF NOT EXISTS `baza`.`kosarica` (
  `id_kosarica` INT(11) NOT NULL AUTO_INCREMENT,
  `datum` DATETIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `fk_id_uporabnik` INT(11) NULL DEFAULT NULL,
  UNIQUE INDEX `id_narocilo_UNIQUE` (`id_kosarica` ASC),
  PRIMARY KEY (`id_kosarica`),
  INDEX `fk_narocilo_uporabnik1_idx` (`fk_id_uporabnik` ASC),
  CONSTRAINT `fk_id_uporabnik`
    FOREIGN KEY (`fk_id_uporabnik`)
    REFERENCES `baza`.`uporabnik` (`id_uporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`avto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`avto` ;

CREATE TABLE IF NOT EXISTS `baza`.`avto` (
  `id_avto` INT(11) NOT NULL AUTO_INCREMENT,
  `marka` VARCHAR(45) NOT NULL,
  `cena` INT(20) NOT NULL,
  `aktiven` INT(11) NOT NULL,
  `opis` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_avto`),
  UNIQUE INDEX `id_avto_UNIQUE` (`id_avto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`kosarica_avto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`kosarica_avto` ;

CREATE TABLE IF NOT EXISTS `baza`.`kosarica_avto` (
  `fk_id_k` INT(11) NULL DEFAULT NULL,
  `fk_id_a` INT(11) NULL DEFAULT NULL,
  `kolicina` INT(11) NOT NULL,
  INDEX `fk_kosarica_avto_kosarica1_idx` (`fk_id_k` ASC),
  INDEX `fk_kosarica_avto_avto1_idx` (`fk_id_a` ASC),
  CONSTRAINT `fk_id_k`
    FOREIGN KEY (`fk_id_k`)
    REFERENCES `baza`.`kosarica` (`id_kosarica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_a`
    FOREIGN KEY (`fk_id_a`)
    REFERENCES `baza`.`avto` (`id_avto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`avto_slika`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`avto_slika` ;

CREATE TABLE IF NOT EXISTS `baza`.`avto_slika` (
  `slika` VARCHAR(100) NOT NULL,
  `fk_id_avto` INT(11) NULL DEFAULT NULL,
  INDEX `fk_avto_slika_avto1_idx` (`fk_id_avto` ASC),
  CONSTRAINT `fk_id_avto`
    FOREIGN KEY (`fk_id_avto`)
    REFERENCES `baza`.`avto` (`id_avto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baza`.`dnevnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baza`.`dnevnik` ;

CREATE TABLE IF NOT EXISTS `baza`.`dnevnik` (
  `sodrzina` VARCHAR(200) NOT NULL,
  `fk_id_u` INT(11) NULL DEFAULT NULL,
  INDEX `fk_dnevnik_uporabnik1_idx` (`fk_id_u` ASC),
  CONSTRAINT `fk_id_u`
    FOREIGN KEY (`fk_id_u`)
    REFERENCES `baza`.`uporabnik` (`id_uporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `baza`.`naslov`
-- -----------------------------------------------------
START TRANSACTION;
USE `baza`;
INSERT INTO `baza`.`naslov` (`id_naslov`, `postna_stevilka`, `mesto`, `ulica`, `hisna_stevilka`) VALUES (DEFAULT, 1000, 'Ljubljana', 'Neubergerjeva', '21');
INSERT INTO `baza`.`naslov` (`id_naslov`, `postna_stevilka`, `mesto`, `ulica`, `hisna_stevilka`) VALUES (DEFAULT, 1000, 'Ljubljana', 'Kolajbova', '22');
INSERT INTO `baza`.`naslov` (`id_naslov`, `postna_stevilka`, `mesto`, `ulica`, `hisna_stevilka`) VALUES (DEFAULT, 2000, 'Maribor', 'Slovenska cesta', '53');
INSERT INTO `baza`.`naslov` (`id_naslov`, `postna_stevilka`, `mesto`, `ulica`, `hisna_stevilka`) VALUES (DEFAULT, 4000, 'Kranj', 'Sorlijeva ulica', '124');

COMMIT;


-- -----------------------------------------------------
-- Data for table `baza`.`uporabnik`
-- -----------------------------------------------------
START TRANSACTION;
USE `baza`;
INSERT INTO `baza`.`uporabnik` (`id_uporabnik`, `ime`, `priimek`, `email`, `geslo`, `telefon`, `status`, `uloga`, `fk_id_naslov`) VALUES (DEFAULT, 'Admin', 'Admin', 'admin@gmail.com', 'Admin123', NULL, 'aktiven', 'admin', NULL);
INSERT INTO `baza`.`uporabnik` (`id_uporabnik`, `ime`, `priimek`, `email`, `geslo`, `telefon`, `status`, `uloga`, `fk_id_naslov`) VALUES (DEFAULT, 'Emil', 'Batakliev', 'emil@gmail.com', 'Emil123', NULL, 'deaktiviran', 'prodajalec', NULL);
INSERT INTO `baza`.`uporabnik` (`id_uporabnik`, `ime`, `priimek`, `email`, `geslo`, `telefon`, `status`, `uloga`, `fk_id_naslov`) VALUES (DEFAULT, 'Martin', 'Arsovski', 'martin@gmail.com', 'Martin123', NULL, 'aktiven', 'prodajalec', NULL);
INSERT INTO `baza`.`uporabnik` (`id_uporabnik`, `ime`, `priimek`, `email`, `geslo`, `telefon`, `status`, `uloga`, `fk_id_naslov`) VALUES (DEFAULT, 'Maja', 'Nikoloska', 'maja@gmail.com', 'Maja123', NULL, 'aktiven', 'prodajalec', NULL);
INSERT INTO `baza`.`uporabnik` (`id_uporabnik`, `ime`, `priimek`, `email`, `geslo`, `telefon`, `status`, `uloga`, `fk_id_naslov`) VALUES (DEFAULT, 'Luka', 'Doncic', 'luka@gmail.com', 'Luka123', '030123123', 'aktiven', 'stranka', 2);
INSERT INTO `baza`.`uporabnik` (`id_uporabnik`, `ime`, `priimek`, `email`, `geslo`, `telefon`, `status`, `uloga`, `fk_id_naslov`) VALUES (DEFAULT, 'Goran', 'Dragic', 'goran@gmail.com', 'Goran123', '030987987', 'aktiven', 'stranka', 1);
INSERT INTO `baza`.`uporabnik` (`id_uporabnik`, `ime`, `priimek`, `email`, `geslo`, `telefon`, `status`, `uloga`, `fk_id_naslov`) VALUES (DEFAULT, 'Ana', 'Novak', 'ana@gmail.com', 'Ana123', '070123456', 'aktiven', 'stranka', 3);
INSERT INTO `baza`.`uporabnik` (`id_uporabnik`, `ime`, `priimek`, `email`, `geslo`, `telefon`, `status`, `uloga`, `fk_id_naslov`) VALUES (DEFAULT, 'Janez', 'Drsko', 'janez@gmail.com', 'Janez123', '031111222', 'deaktiviran', 'stranka', 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `baza`.`kosarica`
-- -----------------------------------------------------
START TRANSACTION;
USE `baza`;
INSERT INTO `baza`.`kosarica` (`id_kosarica`, `datum`, `status`, `fk_id_uporabnik`) VALUES (DEFAULT, '2019-12-22 16:42:12', 'neobdelano', 5);
INSERT INTO `baza`.`kosarica` (`id_kosarica`, `datum`, `status`, `fk_id_uporabnik`) VALUES (DEFAULT, '2019-11-25 09:15:54', 'potrjeno', 6);
INSERT INTO `baza`.`kosarica` (`id_kosarica`, `datum`, `status`, `fk_id_uporabnik`) VALUES (DEFAULT, '2020-01-10 15:35:03', 'preklicano', 8);
INSERT INTO `baza`.`kosarica` (`id_kosarica`, `datum`, `status`, `fk_id_uporabnik`) VALUES (DEFAULT, '2020-01-07 22:32:32', 'stornirano', 7);
INSERT INTO `baza`.`kosarica` (`id_kosarica`, `datum`, `status`, `fk_id_uporabnik`) VALUES (DEFAULT, '2019-12-20 11:47:10', 'potrjeno', 5);
INSERT INTO `baza`.`kosarica` (`id_kosarica`, `datum`, `status`, `fk_id_uporabnik`) VALUES (DEFAULT, '2019-01-01 09:15:00', 'neobdelano', 6);

COMMIT;


-- -----------------------------------------------------
-- Data for table `baza`.`avto`
-- -----------------------------------------------------
START TRANSACTION;
USE `baza`;
INSERT INTO `baza`.`avto` (`id_avto`, `marka`, `cena`, `aktiven`, `opis`) VALUES (DEFAULT, 'ferrari', 674500, 1, 'Najboljsi avto. Zelo hiter.');
INSERT INTO `baza`.`avto` (`id_avto`, `marka`, `cena`, `aktiven`, `opis`) VALUES (DEFAULT, 'lamborghini', 595200, 1, 'Super avto. Vsakemu je vsec.');
INSERT INTO `baza`.`avto` (`id_avto`, `marka`, `cena`, `aktiven`, `opis`) VALUES (DEFAULT, 'bmw', 110500, 1, 'Res dobar BMW.');
INSERT INTO `baza`.`avto` (`id_avto`, `marka`, `cena`, `aktiven`, `opis`) VALUES (DEFAULT, 'audi', 120000, 1, 'Audi ki je zelo mocan in hiter.');
INSERT INTO `baza`.`avto` (`id_avto`, `marka`, `cena`, `aktiven`, `opis`) VALUES (DEFAULT, 'mercedes', 115000, 1, 'Mercedes je mercedes.');
INSERT INTO `baza`.`avto` (`id_avto`, `marka`, `cena`, `aktiven`, `opis`) VALUES (DEFAULT, 'opel', 25000, 1, 'Super cela za dobar avto.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `baza`.`kosarica_avto`
-- -----------------------------------------------------
START TRANSACTION;
USE `baza`;
INSERT INTO `baza`.`kosarica_avto` (`fk_id_k`, `fk_id_a`, `kolicina`) VALUES (1, 2, 1);
INSERT INTO `baza`.`kosarica_avto` (`fk_id_k`, `fk_id_a`, `kolicina`) VALUES (6, 6, 2);
INSERT INTO `baza`.`kosarica_avto` (`fk_id_k`, `fk_id_a`, `kolicina`) VALUES (5, 1, 1);
INSERT INTO `baza`.`kosarica_avto` (`fk_id_k`, `fk_id_a`, `kolicina`) VALUES (3, 5, 3);
INSERT INTO `baza`.`kosarica_avto` (`fk_id_k`, `fk_id_a`, `kolicina`) VALUES (4, 3, 2);
INSERT INTO `baza`.`kosarica_avto` (`fk_id_k`, `fk_id_a`, `kolicina`) VALUES (2, 4, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `baza`.`avto_slika`
-- -----------------------------------------------------
START TRANSACTION;
USE `baza`;
INSERT INTO `baza`.`avto_slika` (`slika`, `fk_id_avto`) VALUES ('ferrari', 1);
INSERT INTO `baza`.`avto_slika` (`slika`, `fk_id_avto`) VALUES ('lamborghini', 2);
INSERT INTO `baza`.`avto_slika` (`slika`, `fk_id_avto`) VALUES ('audi', 4);
INSERT INTO `baza`.`avto_slika` (`slika`, `fk_id_avto`) VALUES ('bmw', 3);
INSERT INTO `baza`.`avto_slika` (`slika`, `fk_id_avto`) VALUES ('mercedes', 5);
INSERT INTO `baza`.`avto_slika` (`slika`, `fk_id_avto`) VALUES ('opel', 6);
INSERT INTO `baza`.`avto_slika` (`slika`, `fk_id_avto`) VALUES ('ferrari2', 1);
INSERT INTO `baza`.`avto_slika` (`slika`, `fk_id_avto`) VALUES ('mercedes2', 5);
INSERT INTO `baza`.`avto_slika` (`slika`, `fk_id_avto`) VALUES ('bmw2', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `baza`.`dnevnik`
-- -----------------------------------------------------
START TRANSACTION;
USE `baza`;
INSERT INTO `baza`.`dnevnik` (`sodrzina`, `fk_id_u`) VALUES ('nekoja sodrzina', 1);
INSERT INTO `baza`.`dnevnik` (`sodrzina`, `fk_id_u`) VALUES ('nekoja sodrzina', 2);
INSERT INTO `baza`.`dnevnik` (`sodrzina`, `fk_id_u`) VALUES ('nekoja sodrzina', 3);
INSERT INTO `baza`.`dnevnik` (`sodrzina`, `fk_id_u`) VALUES ('nekoja sodrzina', 4);
INSERT INTO `baza`.`dnevnik` (`sodrzina`, `fk_id_u`) VALUES ('nekoja sodrzina', NULL);

COMMIT;

